board_cards = ["", "", "", "", ""]
hand_commitments = ["", "", "", "", "", ""]
hole_card1 = ["", "", "", "", "", ""]
hole_card2 = ["", "", "", "", "", ""]
num_active_players = ""
salts1 = ["", "", "", "", "", ""]
salts2 = ["", "", "", "", "", ""]
winner_index = ""
