deck = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
deck_root = ""
num_previously_used = ""
num_revealed = ""
previously_used_indices = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
revealed_cards = ["", "", ""]
revealed_indices = ["", "", ""]
salts = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
