# co-noir REP3 party configuration for Node 2 (local development)

[network]
my_id = 2
bind_addr = "0.0.0.0:10002"
key_path = "services/node/data/key2.der"
max_frame_length = 469_762_056

[[network.parties]]
id = 0
dns_name = "127.0.0.1:10000"
cert_path = "services/node/data/cert0.der"

[[network.parties]]
id = 1
dns_name = "127.0.0.1:10001"
cert_path = "services/node/data/cert1.der"

[[network.parties]]
id = 2
dns_name = "127.0.0.1:10002"
cert_path = "services/node/data/cert2.der"
